"""bookstock created_on column added

Revision ID: 8f042a1d8329
Revises: d35efa8e2301
Create Date: 2024-10-20 23:58:50.139169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f042a1d8329'
down_revision = 'd35efa8e2301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_stock', schema=None) as batch_op:
        batch_op.drop_column('created_on')

    # ### end Alembic commands ###
