"""initial migration

Revision ID: ab66ca88a19c
Revises: 
Create Date: 2024-10-17 15:08:27.856951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab66ca88a19c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('language',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('publisher',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('isbn', sa.String(length=10), nullable=False),
    sa.Column('isbn13', sa.String(length=13), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('num_pages', sa.Integer(), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=False),
    sa.Column('publisher_name', sa.String(length=50), nullable=False),
    sa.Column('average_rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('ratings_count', sa.Integer(), nullable=False),
    sa.Column('text_reviews_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_code'], ['language.code'], ),
    sa.ForeignKeyConstraint(['publisher_name'], ['publisher.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_author_table',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'author_id')
    )
    op.create_table('book_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('TAKEN', 'AVAILABLE', name='stockstatus'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_id'], ['book_stock.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_trans_id', sa.Integer(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('extra_days', sa.Integer(), nullable=False),
    sa.Column('total_fine', sa.Integer(), nullable=False),
    sa.Column('total_rent', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PAID', 'DUE', name='transactionstatus'), nullable=False),
    sa.ForeignKeyConstraint(['book_trans_id'], ['book_transaction.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('book_transaction')
    op.drop_table('book_stock')
    op.drop_table('book_author_table')
    op.drop_table('book')
    op.drop_table('publisher')
    op.drop_table('member')
    op.drop_table('language')
    op.drop_table('author')
    # ### end Alembic commands ###
